name: require_trailing_commas_custom
description: A modified version of the require_trailing_commas lint rule that behaves like ESLint’s comma-dangle with the always-multiline option.
version: 1.0.3
repository: https://github.com/chika3742/require_trailing_commas_custom

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.5
  custom_lint_builder: ^0.8.1

dev_dependencies:
  lints: ^5.0.0
